module.exports = {
  HASHTAG_LABELS: [
    "#coleraalegria",
    "#desenhospelademocracia",
    "#designativista",
    "#foragarimpoforacovid",
    "#projetemos",
    "#mariellepresente",
    "hashtag__test",
  ],

  TAGS: [
    "amazonia",
    "aquecimento global",
    "brumadinho",
    "crime ambiental",
    "desastre ambiental",
    "fumaça",
    "indígenas",
    "meio ambiente",
    "mineração",
    "oleo ",
    "petroleo",
    "praia contaminada",
    "queimadas",
    "previdência",
    "reforma trabalhista",
    "arte",
    "bolsonaro",
    "brasil",
    "brazilresists",
    "caixa2dobolsonaro",
    "cirogomes",
    "cultura",
    "democracia",
    "dilma",
    "direitoshumanos",
    "ditaduranuncamais",
    "diversidade",
    "doria",
    "educação",
    "educaçãoinclusiva",
    "eleicoes2018",
    "eleições2018",
    "elenunca",
    "esquerda",
    "facistas",
    "feminismo",
    "foratemer",
    "golpista",
    "grevegeral",
    "haddad",
    "história",
    "homofobia",
    "impeachmentbolsonaro",
    "justiça",
    "lgbt",
    "lgbtq",
    "liberdade",
    "lulalivre",
    "lula",
    "machismo",
    "mariellevive ",
    "mexeucomumamexeucomtodas",
    "moro",
    "movimentonegro",
    "mulherescontrabolsonaro",
    "mulheresnapolitica",
    "mulheresunidaspelademocracia",
    "negra",
    "ninguemsoltaamãodeninguem",
    "quemmatoumarielle",
    "racismo",
    "redeglobo",
    "resistencia",
    "sociedade",
    "tsunamidaeducação",
    "vazajato",
    "vidasnegrasimportam",
  ].sort(),


  LABELS: [
    'F'
  ],

  // ID of the backup folder in Google Drive
  FOLDER_ID: "1UlkoCZ1jjEdPI8CwC2dViBFI-QyUVaK7",
};
